### ISSUE TITLE
[BE] 마일스톤 TODO 아이템 CRUD API

### ISSUE THREAD

**Issue by JiHyeonL** [woowacourse-teams/2024-coduo#225]
- [ ] 스웨거 API 문서 추가
- [x] API 구현
  - [x] 투두 리스트 전체 조회
  - [ ] 투두 아이템 생성
  - [x] 투두 아이템 내용 수정
  - [ ] 투두 아이템 순서 변경
  - [x] 투두 아이템 체크 여부 토글
  - [x] 투구 아이템 삭제
- [x] API 테스팅
